
networks:
 resPatNetworks: # Definir la red para la comunicación entre servicios
    driver: bridge

services:
  app_respat:
    build: 
      context: ./residuosPatologicos_backEnd
      dockerfile: DockerFile
    container_name: app_respat
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db_residuoPat:3306/residuos_Patologicos?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      residuos_pat:
        condition: service_healthy
    networks:
      - resPatNetworks

  residuos_pat:
    image: mysql:8.0.33
    container_name: db_residuoPat
    ports:
      - "3307:3306"  # Solo si necesitas acceso externo a MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: residuos_Patologicos
      MYSQL_ROOT_HOST: "%"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - resPatNetworks

  frontEnd:
    image: respat-frontend
    build:
      context: ./ResiduoPat_FrontEnd
      dockerfile: Dockerfile
    container_name: angular_respat
    ports:
      - "80:80"
    restart: always
    depends_on:
      app_respat:
        condition: service_started
    networks:
      - resPatNetworks

volumes:
  db_data:
