
networks:
 resPatNetworks: # Definir la red para la comunicación entre servicios
    driver: bridge

services:
  app_respat:
    build: 
      context: ./residuosPatologicos_backEnd
      dockerfile: DockerFile
    container_name: app_respat
    mem_limit: 512m
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://residuos_pat:3306/residuos_Patologicos?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      start_period: 40s  
    restart: always
    depends_on:
      residuos_pat:
        condition: service_healthy
    networks:
      - resPatNetworks

  residuos_pat:
    image: mysql:8.0.33
    container_name: db_residuoPat
    ports:
      - "3307:3306"  # Solo si necesitas acceso externo a MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: residuos_Patologicos
      MYSQL_ROOT_HOST: "%"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p1234 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - resPatNetworks
  nginx:
    image: nginx:latest
    container_name: nginx_respat
    ports:
      - "80:80"
    volumes:
      - ./ResiduoPat_FrontEnd/dist/frontend-admin-residuos:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/custom.conf
    depends_on:
      - app_respat
    networks:
      - resPatNetworks    
volumes:
  db_data:
